### ISSUE TITLE
No instructions on how to run after installing

### ISSUE THREAD

**Issue by rmsilva1973** [MicrosoftDocs/WSL.pt-BR#4]
I've installed the Linux Kernel Update package, however the article doesn't tell me how to execute it after installing...

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [Atualizar o kernel do WSL 2 Linux](https://docs.microsoft.com/pt-br/windows/wsl/wsl2-kernel#feedback)
* Content Source: [WSL/wsl2-kernel.md](https://github.com/MicrosoftDocs/WSL.pt-br/blob/live/WSL/wsl2-kernel.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by srvbpigh** [comment]
Hello, @rmsilva1973
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @rmsilva1973, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/WSL/issues/658. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
